server:
  port: 8080

app:
  upload:
    dir: ./uploads

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/game_guide?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&serverTimezone=Asia/Shanghai
    username: root
    password: li123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gameguide.entity
  configuration:
    map-underscore-to-camel-case: true
